import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, BadgeCheck, Check, ChevronDown, ChevronLeft, ChevronRight, Heart, Minus, Plus, Search, ShieldCheck, ShoppingBag, Star, Truck, UserRound, X, SlidersHorizontal, Sparkles, CreditCard, PackageCheck, Trash2 } from 'lucide-react';
import { categories, formatINR, products } from './data';

const STORAGE_CART='nova_cart_v1', STORAGE_WISH='nova_wish_v1', STORAGE_ORDERS='nova_orders_v1';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};

export default function App(){
 const [cart,setCart]=useState(()=>read(STORAGE_CART,[]));
 const [wishlist,setWishlist]=useState(()=>read(STORAGE_WISH,[]));
 const [orders,setOrders]=useState(()=>read(STORAGE_ORDERS,[]));
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [sort,setSort]=useState('featured');
 const [maxPrice,setMaxPrice]=useState(90000); const [rating,setRating]=useState(0); const [showFilters,setShowFilters]=useState(false);
 const [cartOpen,setCartOpen]=useState(false); const [accountOpen,setAccountOpen]=useState(false); const [product,setProduct]=useState(null); const [checkout,setCheckout]=useState(false); const [notice,setNotice]=useState('');
 useEffect(()=>localStorage.setItem(STORAGE_CART,JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem(STORAGE_WISH,JSON.stringify(wishlist)),[wishlist]); useEffect(()=>localStorage.setItem(STORAGE_ORDERS,JSON.stringify(orders)),[orders]);
 const filtered=useMemo(()=>{let a=products.filter(p=>(category==='All'||p.category===category)&&p.price<=maxPrice&&p.rating>=rating&&`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query.toLowerCase())); if(sort==='price-low')a.sort((x,y)=>x.price-y.price); if(sort==='price-high')a.sort((x,y)=>y.price-x.price); if(sort==='rating')a.sort((x,y)=>y.rating-x.rating); return a},[query,category,maxPrice,rating,sort]);
 const cartCount=cart.reduce((s,i)=>s+i.qty,0), subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0), shipping=subtotal>=5000||subtotal===0?0:149, total=subtotal+shipping;
 const add=(p)=>{setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setNotice(`${p.name} added to cart`);setTimeout(()=>setNotice(''),1800)};
 const change=(id,delta)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+delta}:i).filter(i=>i.qty>0));
 const toggleWish=(id)=>setWishlist(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
 const resetFilters=()=>{setCategory('All');setMaxPrice(90000);setRating(0);setQuery('');setSort('featured')};
 const placeOrder=(details)=>{const order={id:`NOVA-${Date.now().toString().slice(-6)}`,date:new Date().toLocaleDateString('en-IN'),items:cart,total,status:'Confirmed',customer:details};setOrders(o=>[order,...o]);setCart([]);setCheckout(false);setCartOpen(false);setNotice(`Order ${order.id} confirmed`);setTimeout(()=>setNotice(''),2600)};
 return <div className="site">
  <div className="topbar"><span>Free delivery on orders above ₹5,000</span><span className="toplinks">Easy returns · Secure checkout · 24/7 support</span></div>
  <header className="header"><div className="header-inner">
   <a className="logo" href="#home">NOVA<span>.</span></a>
   <nav>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>{setCategory(c);document.getElementById('shop').scrollIntoView({behavior:'smooth'})}}>{c}</button>)}</nav>
   <div className="header-actions"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/><kbd>⌘ K</kbd></div><button className="icon-btn" onClick={()=>setAccountOpen(true)}><UserRound size={19}/></button><button className="bag-btn" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><span>{cartCount}</span></button></div>
  </div></header>
  <main id="home">
   <section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="pill"><Sparkles size={14}/> Curated for modern living</span><h1>Better products.<br/><em>Better everyday.</em></h1><p>Thoughtfully selected technology, audio and workspace essentials — designed to help you do more with less.</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById('shop').scrollIntoView({behavior:'smooth'})}>Shop collection <ArrowRight size={17}/></button><button className="ghost" onClick={()=>setCategory('Tech')}>Explore tech</button></div><div className="trust-row"><span><ShieldCheck size={16}/> Secure payments</span><span><Truck size={16}/> Fast delivery</span><span><BadgeCheck size={16}/> Curated quality</span></div></div><div className="hero-product"><div className="hero-glow"/><img src={products[0].image} alt="AeroBook Pro 14"/><div className="floating-card"><span>Featured pick</span><strong>AeroBook Pro 14</strong><small>From {formatINR(products[0].price)}</small></div></div></div></section>
   <section className="benefits"><div><Truck/><div><strong>Free delivery</strong><span>On orders above ₹5,000</span></div></div><div><ShieldCheck/><div><strong>Secure checkout</strong><span>Protected payments</span></div></div><div><PackageCheck/><div><strong>Easy returns</strong><span>7-day return window</span></div></div><div><BadgeCheck/><div><strong>Quality checked</strong><span>Curated products</span></div></div></section>
   <section id="shop" className="shop section"><div className="section-head"><div><span className="eyebrow">THE COLLECTION</span><h2>Shop our picks</h2><p>{filtered.length} products selected for you</p></div><div className="sort"><button onClick={()=>setShowFilters(v=>!v)}><SlidersHorizontal size={17}/> Filters</button><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="rating">Top rated</option></select><ChevronDown size={15}/></label></div></div>
    <AnimatePresence>{showFilters&&<motion.div className="filters" initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}><div><strong>Category</strong><div className="filter-pills">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div><div><strong>Price up to {formatINR(maxPrice)}</strong><input type="range" min="2000" max="90000" step="1000" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)}/></div><div><strong>Minimum rating</strong><div className="stars-filter">{[4,4.5,4.8].map(r=><button key={r} className={rating===r?'active':''} onClick={()=>setRating(r)}><Star size={14} fill="currentColor"/> {r}+</button>)}</div></div><button className="reset" onClick={resetFilters}>Reset all</button></motion.div>}</AnimatePresence>
    <div className="product-grid">{filtered.map(p=><ProductCard key={p.id} p={p} wished={wishlist.includes(p.id)} onWish={()=>toggleWish(p.id)} onView={()=>setProduct(p)} onAdd={()=>add(p)}/>)}</div>{filtered.length===0&&<div className="empty"><Search size={30}/><h3>No products found</h3><p>Try a different search or reset your filters.</p><button className="primary" onClick={resetFilters}>Reset filters</button></div>}
   </section>
   <section className="banner section"><div><span className="eyebrow">NOVA SELECT</span><h2>Upgrade your workspace.</h2><p>From focused lighting to crisp 4K displays, build a desk that makes good work feel effortless.</p><button className="light-btn" onClick={()=>{setCategory('Workspace');document.getElementById('shop').scrollIntoView({behavior:'smooth'})}}>Shop workspace <ArrowRight size={17}/></button></div><div className="banner-stack"><img src={products[4].image}/><img src={products[7].image}/></div></section>
   <section className="newsletter section"><div><span className="eyebrow">STAY IN THE LOOP</span><h2>Good products, no inbox noise.</h2><p>Get occasional drops, price updates and buying guides.</p></div><form onSubmit={e=>{e.preventDefault();setNotice('You are on the NOVA list ✓');setTimeout(()=>setNotice(''),2200)}}><input required type="email" placeholder="you@example.com"/><button className="primary">Subscribe <ArrowRight size={16}/></button></form></section>
  </main>
  <footer><div className="footer-inner"><div><a className="logo" href="#home">NOVA<span>.</span></a><p>Modern commerce, thoughtfully curated.</p></div><div><strong>Shop</strong><a>Tech</a><a>Audio</a><a>Workspace</a><a>Lifestyle</a></div><div><strong>Help</strong><a>Shipping</a><a>Returns</a><a>Payments</a><a>Support</a></div><div><strong>Built for the portfolio</strong><p className="muted">React · Vite · Framer Motion · LocalStorage · Sandbox checkout</p></div></div><div className="copyright">© {new Date().getFullYear()} NOVA Commerce · Demo storefront for educational use.</div></footer>
  <AnimatePresence>{cartOpen&&<CartDrawer cart={cart} subtotal={subtotal} shipping={shipping} total={total} change={change} onClose={()=>setCartOpen(false)} onCheckout={()=>setCheckout(true)}/>}</AnimatePresence>
  <AnimatePresence>{product&&<ProductModal p={product} wished={wishlist.includes(product.id)} onWish={()=>toggleWish(product.id)} onAdd={()=>add(product)} onClose={()=>setProduct(null)}/>}</AnimatePresence>
  <AnimatePresence>{checkout&&<Checkout total={total} onClose={()=>setCheckout(false)} onPlace={placeOrder}/>}</AnimatePresence>
  <AnimatePresence>{accountOpen&&<Account orders={orders} onClose={()=>setAccountOpen(false)}/>}</AnimatePresence>
  <AnimatePresence>{notice&&<motion.div className="toast" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}}><Check size={17}/>{notice}</motion.div>}</AnimatePresence>
 </div>
}

function ProductCard({p,wished,onWish,onView,onAdd}){return <motion.article className="product-card" whileHover={{y:-5}}><div className={`product-image ${p.color}`}><img src={p.image} alt={p.name}/><span className="badge">{p.badge}</span><button className={wished?'wish active':'wish'} onClick={onWish} aria-label="Wishlist"><Heart size={18} fill={wished?'currentColor':'none'}/></button><button className="quick" onClick={onView}>Quick view</button></div><div className="product-info"><div className="rating"><Star size={14} fill="currentColor"/> {p.rating} <span>({p.reviews})</span></div><h3 onClick={onView}>{p.name}</h3><p>{p.description}</p><div className="price-row"><div><strong>{formatINR(p.price)}</strong>{p.oldPrice&&<del>{formatINR(p.oldPrice)}</del>}</div><button className="add" onClick={onAdd}><Plus size={17}/></button></div></div></motion.article>}

function CartDrawer({cart,subtotal,shipping,total,change,onClose,onCheckout}){return <motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.aside className="drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><div className="drawer-head"><div><span className="eyebrow">YOUR BAG</span><h2>{cart.reduce((s,i)=>s+i.qty,0)} items</h2></div><button className="close" onClick={onClose}><X/></button></div>{cart.length===0?<div className="empty cart-empty"><ShoppingBag size={38}/><h3>Your bag is empty</h3><p>Add something you love from the collection.</p><button className="primary" onClick={onClose}>Continue shopping</button></div>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><img src={i.image} alt=""/><div><strong>{i.name}</strong><span>{formatINR(i.price)}</span><div className="qty"><button onClick={()=>change(i.id,-1)}><Minus size={14}/></button><b>{i.qty}</b><button onClick={()=>change(i.id,1)}><Plus size={14}/></button></div></div><button className="remove" onClick={()=>change(i.id,-i.qty)}><Trash2 size={16}/></button></div>)}</div><div className="summary"><div><span>Subtotal</span><strong>{formatINR(subtotal)}</strong></div><div><span>Shipping</span><strong>{shipping===0?'FREE':formatINR(shipping)}</strong></div><div className="total"><span>Total</span><strong>{formatINR(total)}</strong></div><button className="checkout-btn" onClick={onCheckout}>Proceed to checkout <ArrowRight size={17}/></button><small>Sandbox payment · No real charge</small></div></>}</motion.aside></motion.div>}

function ProductModal({p,wished,onWish,onAdd,onClose}){return <div className="modal-wrap"><motion.div className="modal product-modal" initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}}><button className="close modal-close" onClick={onClose}><X/></button><div className="modal-image"><img src={p.image} alt={p.name}/></div><div className="modal-copy"><span className="eyebrow">{p.category} · {p.badge}</span><h2>{p.name}</h2><div className="rating big"><Star size={16} fill="currentColor"/> {p.rating} <span>{p.reviews} reviews</span></div><p>{p.description}</p><ul>{p.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><div className="modal-price">{formatINR(p.price)} {p.oldPrice&&<del>{formatINR(p.oldPrice)}</del>}</div><div className="modal-actions"><button className="primary" onClick={()=>{onAdd();onClose()}}>Add to cart <ShoppingBag size={17}/></button><button className={wished?'secondary active':'secondary'} onClick={onWish}><Heart size={17} fill={wished?'currentColor':'none'}/> {wished?'Saved':'Wishlist'}</button></div><small className="stock">Only {p.stock} left · Ships within 24 hours</small></div></motion.div></div>}

function Checkout({total,onClose,onPlace}){const [method,setMethod]=useState('card'); const [form,setForm]=useState({name:'',email:'',address:'',city:'',pin:''}); const submit=e=>{e.preventDefault();onPlace(form)}; return <div className="modal-wrap"><motion.div className="modal checkout" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="drawer-head"><div><span className="eyebrow">SECURE CHECKOUT</span><h2>Complete your order</h2></div><button className="close" onClick={onClose}><X/></button></div><div className="steps"><span className="done">1 · Delivery</span><span>2 · Payment</span><span>3 · Confirmation</span></div><form onSubmit={submit}><div className="form-grid"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="wide">Address<input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>PIN code<input required pattern="[0-9]{6}" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})}/></label></div><div className="pay-method"><strong>Payment method</strong><div><button type="button" className={method==='card'?'selected':''} onClick={()=>setMethod('card')}><CreditCard size={18}/> Card</button><button type="button" className={method==='upi'?'selected':''} onClick={()=>setMethod('upi')}>UPI</button><button type="button" className={method==='cod'?'selected':''} onClick={()=>setMethod('cod')}>COD</button></div></div><div className="checkout-bottom"><div><span>Total payable</span><strong>{formatINR(total)}</strong></div><button className="checkout-btn" type="submit">{method==='cod'?'Place order':'Pay in sandbox'} <ArrowRight size={17}/></button></div><p className="sandbox-note"><ShieldCheck size={15}/> This portfolio demo uses a sandbox-style payment flow. No real payment is processed.</p></form></motion.div></div>}

function Account({orders,onClose}){return <div className="modal-wrap"><motion.div className="modal account" initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}}><button className="close modal-close" onClick={onClose}><X/></button><span className="eyebrow">ACCOUNT</span><h2>Your orders</h2>{orders.length===0?<div className="empty"><PackageCheck size={34}/><h3>No orders yet</h3><p>Your confirmed orders will appear here.</p></div>:<div className="orders">{orders.map(o=><div className="order" key={o.id}><div><strong>{o.id}</strong><span>{o.date} · {o.items.reduce((s,i)=>s+i.qty,0)} items</span></div><div><b>{formatINR(o.total)}</b><small><Check size={13}/> {o.status}</small></div></div>)}</div>}</motion.div></div>}
